# Generated by Django 4.2.1 on 2023-05-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottwebapp', '0002_remove_videolist_video_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoList',
        ),
    ]
