# Generated by Django 4.2.1 on 2023-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottwebapp', '0003_delete_videolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_category', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=511)),
                ('video_name', models.CharField(max_length=255)),
            ],
        ),
    ]
