# Generated by Django 4.2.1 on 2023-05-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottwebapp', '0005_customuser_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
