# Generated by Django 4.2.1 on 2023-05-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottwebapp', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveVideos',
            new_name='SaveVideo',
        ),
    ]
