# Generated by Django 4.2.1 on 2023-05-19 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ottwebapp', '0007_rename_savevideos_savevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savevideo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savevideo',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottwebapp.videolist'),
        ),
    ]
