# Generated by Django 3.2 on 2023-05-28 05:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ottwebapp', '0009_watchedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ottwebapp/'),
        ),
        migrations.CreateModel(
            name='StreamingQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_info', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=511)),
                ('content_date', models.DateTimeField(auto_now_add=True)),
                ('bandwidth', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('bitrate_resource', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('resolution', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('streaming_type', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=50)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottwebapp.videolist')),
            ],
        ),
    ]
