# Generated by Django 3.2 on 2023-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottwebapp', '0011_auto_20230528_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocategory',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_category', to='ottwebapp.VideoList'),
        ),
    ]
